### ISSUE TITLE
What is your license?

### ISSUE THREAD

**Issue by white-gecko** [RDFLib/rdflib-web#7]
Under which license do you publish your code?
Is it ok to include parts of your code like this?
https://github.com/AKSW/QuitStore/blob/feature/provenance/quit/plugins/serialisers/results/htmlresults.py

if not, could you please tell us how to include it correctly according to your license terms?

**Comment by white-gecko** [comment]
> Is it ok to include parts of your code like this?
> https://github.com/AKSW/QuitStore/blob/feature/provenance/quit/plugins/serialisers/results/htmlresults.py
> 
> if not, could you please tell us how to include it correctly according to your license terms?

Sorry, I think this file was not taken from your project, I was just confused with the naming …

**Comment by white-gecko** [comment]
Ok now I've taken parts from your file.

**Comment by joernhees** [comment]
@uholzer, @gromgull it's yours... MIT, WTFPL?

**Comment by gromgull** [comment]
I made it MIT - like the rest of RDFLib!
